import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { MantineProvider, Flex, mantineHtmlProps } from "@mantine/core";
import { AppProps } from "next/app";
import "@mantine/core/styles.css";
import { PropsWithChildren } from "react";
// import { theme } from "@/config/theme";
// import TestProvider from "@/Component/TestProvider/TestProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface IRootLayout extends PropsWithChildren, AppProps {
  // children,
  // sideNav: ReactNode;
}

export default function RootLayout({ children }: IRootLayout) {
  return (
    <html lang="en" {...mantineHtmlProps}>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <MantineProvider defaultColorScheme="dark">{children}</MantineProvider>
      </body>
    </html>
  );
}
